name=input("Enter your name")
print('Hello', name)
num1=int(input("Enter a number"))
num2=int(input('Enter another number'))
print("Addition:",num1+num2)
print("Multiplication:",num1*num2)
print("Thank you",name,"\nNice to play with you") #Note \n used in this print()
